package me.drownek.plugwright

import me.drownek.plugwright.api.NpmConfig
import me.drownek.plugwright.api.NpmRegistry
import me.drownek.plugwright.api.SecretRef
import org.gradle.api.GradleException
import org.gradle.api.logging.Logger
import java.io.File
import java.io.IOException
import java.nio.file.Files
import java.nio.file.attribute.PosixFilePermissions
import java.util.Base64

/**
 * Turns the `npm { }` block into the workspace's `.npmrc`, right before something runs
 * `npm install` in it.
 *
 * The file is written at execution time and not a moment earlier: it holds resolved secrets,
 * and the configuration cache is a file on disk like any other.
 *
 * Only a file plugwright wrote itself is ever replaced — the [MARKER] on the first line says
 * so. A workspace with a hand-written `.npmrc` keeps it, and the build says which one won.
 */
internal object NpmrcWriter {

    const val FILE_NAME = ".npmrc"

    const val MARKER = "# Generated by plugwright - do not edit"

    private const val EXPLANATION = "# Edit the npm { } block in your build script instead."

    /**
     * Brings `<workspace>/.npmrc` in line with [config].
     *
     * An empty config removes a file plugwright generated earlier — a registry that has been
     * deleted from the build script should stop applying — and leaves everything else alone.
     */
    fun write(workspace: File, config: NpmConfig, logger: Logger) {
        val file = File(workspace, FILE_NAME)

        if (file.exists() && !isGenerated(file)) {
            if (!config.isEmpty) {
                logger.warn(
                    "${file.absolutePath} was not written by plugwright, so the npm { } block in the " +
                        "build script is being ignored. Delete the file to let plugwright manage it."
                )
            }
            return
        }

        if (config.isEmpty) {
            if (file.exists() && file.delete()) {
                logger.lifecycle("Removed ${file.absolutePath}: no npm { } block declares a registry anymore")
            }
            return
        }

        file.parentFile?.mkdirs()
        file.writeText(render(config))
        restrictPermissions(file)
        logger.lifecycle("Wrote ${file.absolutePath} (${summarize(config)})")
    }

    /** Whether the file is one of ours: the marker is the first thing in it. */
    private fun isGenerated(file: File): Boolean =
        file.useLines { lines -> lines.firstOrNull()?.trim() == MARKER }

    // ---- Rendering ---------------------------------------------------------------------

    private fun render(config: NpmConfig): String = buildString {
        appendLine(MARKER)
        appendLine(EXPLANATION)

        config.registries.forEach { registry ->
            val key = registry.scope?.let { "$it:registry" } ?: "registry"
            appendLine("$key=${registry.url}")
        }

        config.registries.forEach { registry ->
            credentialLines(registry).forEach { appendLine(it) }
        }

        config.options.forEach { (key, value) -> appendLine("$key=$value") }
    }

    private fun credentialLines(registry: NpmRegistry): List<String> {
        val credentials = registry.credentials
        if (credentials.isEmpty) return emptyList()

        val prefix = authKeyPrefix(registry.url)
        val label = registry.scope?.let { "npm scope '$it'" } ?: "the default npm registry"
        val lines = mutableListOf<String>()

        credentials.authToken?.let { lines += "$prefix:_authToken=${resolve(it, label)}" }
        credentials.username?.let { lines += "$prefix:username=${resolve(it, label)}" }
        credentials.password?.let {
            val encoded = Base64.getEncoder().encodeToString(resolve(it, label).toByteArray(Charsets.UTF_8))
            lines += "$prefix:_password=$encoded"
        }
        return lines
    }

    /**
     * The `//host/path/` npm keys credentials hang off, from a registry URL.
     *
     * npm matches these against the registry it is about to talk to, so the path matters:
     * a Nexus with `/repository/npm-private/` authenticates separately from its sibling
     * repositories on the same host.
     */
    private fun authKeyPrefix(url: String): String =
        "//" + url.substringAfter("://").trimEnd('/') + "/"

    // ---- Secrets -----------------------------------------------------------------------

    /**
     * The value behind a [SecretRef], read now rather than at configuration time.
     *
     * A secret that resolves to nothing fails the build here, with the name of what was
     * empty — the alternative is npm answering 401 several minutes into a CI job.
     */
    private fun resolve(ref: SecretRef, label: String): String {
        val (source, value) = when (ref) {
            is SecretRef.FromEnv -> "environment variable '${ref.name}'" to System.getenv(ref.name)
            is SecretRef.FromSystemProperty -> "system property '${ref.name}'" to System.getProperty(ref.name)
            is SecretRef.FromFile -> {
                val file = File(ref.path)
                "file '${ref.path}'" to if (file.isFile) file.useLines { it.firstOrNull() } else null
            }
        }

        if (value.isNullOrBlank()) {
            throw GradleException(
                "The credentials for $label read from $source, which is empty or unset. " +
                    "Set it, or drop the credentials from the npm { } block."
            )
        }
        return value.trim()
    }

    // ---- Housekeeping ------------------------------------------------------------------

    /** Owner-only, on the systems that have a say in it: the file holds tokens. */
    private fun restrictPermissions(file: File) {
        try {
            Files.setPosixFilePermissions(file.toPath(), PosixFilePermissions.fromString("rw-------"))
        } catch (_: UnsupportedOperationException) {
            // Windows: the closest equivalent the java.io API offers.
            file.setReadable(false, false)
            file.setReadable(true, true)
            file.setWritable(false, false)
            file.setWritable(true, true)
        } catch (_: IOException) {
            // Best effort; a file we could write but not chmod is still a working .npmrc.
        }
    }

    /** What went into the file, with the secrets left out of the build log. */
    private fun summarize(config: NpmConfig): String {
        val parts = mutableListOf<String>()

        config.registries.forEach { registry ->
            val name = registry.scope ?: "default"
            val authenticated = if (registry.credentials.isEmpty) "" else ", credentials ***"
            parts += "$name -> ${registry.url}$authenticated"
        }
        if (config.options.isNotEmpty()) {
            parts += "options: ${config.options.keys.joinToString(", ")}"
        }
        return parts.joinToString("; ")
    }
}
